-- Schema Chile. Extra vs Perú: linkedin_posts, events.fecha.

CREATE SCHEMA IF NOT EXISTS chile;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'intranet_chile') THEN
    CREATE ROLE intranet_chile LOGIN NOINHERIT;
  END IF;
END$$;

ALTER ROLE intranet_chile BYPASSRLS;
ALTER ROLE intranet_chile SET search_path = chile;

REVOKE ALL ON SCHEMA chile FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA chile TO intranet_chile;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON SCHEMA chile FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON SCHEMA chile FROM authenticated;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'intranet_peru') THEN
    REVOKE ALL ON SCHEMA chile FROM intranet_peru;
  END IF;
END$$;

-- Enum vacaciones (por schema: el mismo typname en chile y peru no choca)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'vacation_request_status'
      AND n.nspname = 'chile'
  ) THEN
    CREATE TYPE chile.vacation_request_status AS ENUM (
      'pending', 'approved', 'rejected', 'cancelled', 'in_progress', 'completed'
    );
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS chile.work_areas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_name character varying(150) NOT NULL,
  color character varying(7) NOT NULL DEFAULT '#5a6879',
  CONSTRAINT work_areas_area_name_key UNIQUE (area_name),
  CONSTRAINT work_areas_color_hex CHECK (color ~ '^#[0-9A-Fa-f]{6}$')
);

CREATE TABLE IF NOT EXISTS chile.users (
  id integer PRIMARY KEY,
  first_name character varying(100),
  last_name character varying(100),
  email character varying(150),
  password_hash character varying(255),
  password_salt character varying(255),
  role character varying(50),
  email_confirmed boolean DEFAULT false,
  confirm_token character varying(255),
  confirm_expires timestamp without time zone,
  photo text,
  created_at timestamp without time zone DEFAULT now(),
  must_change_password boolean DEFAULT false,
  work_area_id integer REFERENCES chile.work_areas(id),
  birth_date date,
  is_intranet_user boolean NOT NULL DEFAULT true,
  phone numeric,
  home_tutorial_seen boolean NOT NULL DEFAULT true,
  last_login_at timestamp with time zone,
  employment_country character varying(2) NOT NULL DEFAULT 'CL'
    CHECK (employment_country IN ('CL', 'PE')),
  hire_date date,
  manager_user_id integer REFERENCES chile.users(id) ON DELETE SET NULL,
  prior_years_credited numeric(4,1) NOT NULL DEFAULT 0,
  progressive_days_override numeric(4,1),
  work_days_per_week smallint NOT NULL DEFAULT 5
    CHECK (work_days_per_week BETWEEN 3 AND 6),
  CONSTRAINT users_email_key UNIQUE (email)
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique_idx
  ON chile.users (LOWER(TRIM(email)))
  WHERE email IS NOT NULL AND TRIM(email) <> '';

CREATE INDEX IF NOT EXISTS idx_users_employment_country ON chile.users (employment_country);
CREATE INDEX IF NOT EXISTS idx_users_hire_date ON chile.users (hire_date) WHERE hire_date IS NOT NULL;

CREATE TABLE IF NOT EXISTS chile.applications (
  id integer PRIMARY KEY,
  name character varying(255) NOT NULL,
  description text,
  url_pc text,
  url_apk text,
  qr_ios text,
  qr_apk text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  changelog text,
  notified boolean DEFAULT true,
  icon_url text,
  url_ios text,
  url_web text
);

CREATE TABLE IF NOT EXISTS chile.change_log (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES chile.users(id) ON DELETE SET NULL,
  action character varying(255),
  section character varying(100),
  link_path text,
  created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chile.claude_conversations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES chile.users(id) ON DELETE CASCADE,
  title character varying(255) NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_claude_conversations_user_id ON chile.claude_conversations (user_id);
CREATE INDEX IF NOT EXISTS idx_claude_conversations_updated_at ON chile.claude_conversations (updated_at DESC);

CREATE TABLE IF NOT EXISTS chile.claude_daily_usage (
  user_id integer NOT NULL REFERENCES chile.users(id) ON DELETE CASCADE,
  usage_date date NOT NULL DEFAULT CURRENT_DATE,
  message_count integer NOT NULL DEFAULT 0 CHECK (message_count >= 0),
  file_count integer NOT NULL DEFAULT 0 CHECK (file_count >= 0),
  PRIMARY KEY (user_id, usage_date)
);

CREATE TABLE IF NOT EXISTS chile.claude_messages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id integer NOT NULL REFERENCES chile.claude_conversations(id) ON DELETE CASCADE,
  role character varying(20) NOT NULL
    CHECK (role IN ('user', 'assistant')),
  content text NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_claude_messages_conversation_id ON chile.claude_messages (conversation_id);

CREATE TABLE IF NOT EXISTS chile.claude_user_settings (
  user_id integer NOT NULL PRIMARY KEY REFERENCES chile.users(id) ON DELETE CASCADE,
  limits_notice_seen_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS chile.courses (
  id integer PRIMARY KEY,
  title character varying(255) NOT NULL,
  description text,
  material_url text,
  video_url text NOT NULL,
  required_watch_seconds integer NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  commercial_tips text,
  section character varying(255),
  subsection character varying(255)
);

CREATE TABLE IF NOT EXISTS chile.documents (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying(200) NOT NULL,
  type character varying(50) NOT NULL,
  url text NOT NULL,
  public_id character varying(100),
  user_id integer REFERENCES chile.users(id) ON DELETE SET NULL,
  created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chile.events (
  id integer PRIMARY KEY,
  name character varying(200) NOT NULL,
  slug character varying(200) NOT NULL UNIQUE,
  description text,
  image text,
  created_at timestamp without time zone DEFAULT now(),
  fecha text
);

CREATE TABLE IF NOT EXISTS chile.event_photos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id integer REFERENCES chile.events(id) ON DELETE CASCADE,
  url text NOT NULL,
  public_id character varying(100)
);

CREATE TABLE IF NOT EXISTS chile.linkedin_posts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_url text NOT NULL,
  link_url text NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  text text
);


CREATE TABLE IF NOT EXISTS chile.lunch_menu (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_number integer NOT NULL UNIQUE,
  dish_name text NOT NULL
);

CREATE TABLE IF NOT EXISTS chile.news_articles (
  id integer PRIMARY KEY,
  title character varying(255) NOT NULL,
  subtitle character varying(255),
  content text NOT NULL,
  image text,
  public_id character varying(100),
  attachments jsonb DEFAULT '[]'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  slug character varying(100),
  author character varying(100),
  featured boolean NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS idx_news_articles_featured
  ON chile.news_articles (featured) WHERE featured = true;

CREATE TABLE IF NOT EXISTS chile.other_documents (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  url text NOT NULL,
  public_id text,
  created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chile.public_holidays (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_code character varying(2) NOT NULL CHECK (country_code IN ('CL', 'PE')),
  holiday_date date NOT NULL,
  name character varying(200) NOT NULL,
  is_recurring boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE (country_code, holiday_date)
);
CREATE INDEX IF NOT EXISTS idx_public_holidays_country_date
  ON chile.public_holidays (country_code, holiday_date);

CREATE TABLE IF NOT EXISTS chile.questions (
  id integer PRIMARY KEY,
  course_id integer REFERENCES chile.courses(id) ON DELETE CASCADE,
  question_text text NOT NULL,
  sort_order integer DEFAULT 1,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  feedback text
);

CREATE TABLE IF NOT EXISTS chile.question_options (
  id integer PRIMARY KEY,
  question_id integer REFERENCES chile.questions(id) ON DELETE CASCADE,
  text text NOT NULL,
  is_correct boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chile.study_materials (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section character varying(255) NOT NULL,
  name character varying(255) NOT NULL,
  file_url text NOT NULL,
  public_id character varying(255) NOT NULL,
  resource_type character varying(50) NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chile.subsection_details (
  name character varying(255) PRIMARY KEY,
  image_url text
);

CREATE TABLE IF NOT EXISTS chile.support_tickets (
  id integer PRIMARY KEY,
  title character varying(200) NOT NULL,
  description text NOT NULL,
  category character varying(100),
  priority character varying(50),
  status character varying(50) DEFAULT 'Abierto',
  requester_name character varying(150),
  requester_email character varying(150),
  created_at timestamp without time zone DEFAULT now(),
  resolved_at timestamp without time zone,
  closed_at timestamp without time zone,
  auto_closed boolean DEFAULT false,
  attachments text DEFAULT '[]',
  read_by_user boolean DEFAULT true,
  read_by_admin boolean DEFAULT true,
  assigned_to character varying(255)
);

CREATE TABLE IF NOT EXISTS chile.system_config (
  key text PRIMARY KEY,
  value text,
  updated_at timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chile.ticket_replies (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id integer REFERENCES chile.support_tickets(id) ON DELETE CASCADE,
  message text NOT NULL,
  sender character varying(150),
  file_url text,
  file_name text,
  file_type text,
  attachments jsonb DEFAULT '[]'::jsonb,
  created_at timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chile.user_course_progress (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES chile.users(id) ON DELETE CASCADE,
  course_id integer REFERENCES chile.courses(id) ON DELETE CASCADE,
  seconds_watched integer DEFAULT 0,
  status character varying(50) DEFAULT 'en_progreso',
  score numeric(5,2),
  started_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  completed_at timestamp without time zone,
  attempts integer DEFAULT 0,
  UNIQUE (user_id, course_id)
);

CREATE TABLE IF NOT EXISTS chile.vacation_periods (
  id integer PRIMARY KEY,
  user_id integer NOT NULL REFERENCES chile.users(id) ON DELETE CASCADE,
  country_code character varying(2) NOT NULL CHECK (country_code IN ('CL', 'PE')),
  period_start date NOT NULL,
  period_end date NOT NULL,
  entitled_days numeric(5,2) NOT NULL,
  used_days numeric(5,2) NOT NULL DEFAULT 0,
  adjusted_days numeric(5,2) NOT NULL DEFAULT 0,
  expires_at date,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  protected_block_days_used numeric(5,2) NOT NULL DEFAULT 0,
  flexible_block_days_used numeric(5,2) NOT NULL DEFAULT 0,
  record_met boolean NOT NULL DEFAULT true,
  record_validated_by integer REFERENCES chile.users(id) ON DELETE SET NULL,
  record_notes text,
  UNIQUE (user_id, period_start)
);
CREATE INDEX IF NOT EXISTS idx_vacation_periods_user ON chile.vacation_periods (user_id);

CREATE TABLE IF NOT EXISTS chile.vacation_requests (
  id integer PRIMARY KEY,
  user_id integer NOT NULL REFERENCES chile.users(id) ON DELETE CASCADE,
  country_code character varying(2) NOT NULL CHECK (country_code IN ('CL', 'PE')),
  vacation_period_id integer REFERENCES chile.vacation_periods(id) ON DELETE SET NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  business_days numeric(5,2),
  calendar_days integer,
  status chile.vacation_request_status NOT NULL DEFAULT 'pending',
  requester_notes text,
  reviewer_notes text,
  reviewed_by integer REFERENCES chile.users(id) ON DELETE SET NULL,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  fraction_ack_at timestamp with time zone,
  policy_warning_ack boolean NOT NULL DEFAULT false,
  period_allocations jsonb,
  CHECK (end_date >= start_date)
);
CREATE INDEX IF NOT EXISTS idx_vacation_requests_user ON chile.vacation_requests (user_id);
CREATE INDEX IF NOT EXISTS idx_vacation_requests_status ON chile.vacation_requests (status);
CREATE INDEX IF NOT EXISTS idx_vacation_requests_dates ON chile.vacation_requests (start_date, end_date);

CREATE TABLE IF NOT EXISTS chile.vacation_balance_adjustments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vacation_period_id integer NOT NULL REFERENCES chile.vacation_periods(id) ON DELETE CASCADE,
  adjusted_by integer NOT NULL REFERENCES chile.users(id),
  days_delta numeric(5,2) NOT NULL,
  reason text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_vacation_balance_adjustments_period
  ON chile.vacation_balance_adjustments (vacation_period_id);

CREATE OR REPLACE FUNCTION chile.marcar_recuperacion_pass(
  email_input text,
  nuevo_password_hash text
)
RETURNS void
LANGUAGE plpgsql
SET search_path = chile
AS $function$
BEGIN
  UPDATE chile.users
  SET password_hash = nuevo_password_hash,
      must_change_password = TRUE
  WHERE LOWER(email) = LOWER(email_input);

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Usuario con email % no encontrado', email_input;
  END IF;
END;
$function$;

-- RLS activo. intranet_chile tiene BYPASSRLS. Policies: dashboard vs PostgREST.
ALTER TABLE chile.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.change_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.claude_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.claude_daily_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.claude_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.claude_user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.event_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.lunch_menu ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.news_articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.other_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.public_holidays ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.question_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.study_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.subsection_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.system_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.ticket_replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.user_course_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.vacation_balance_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.vacation_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.vacation_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.work_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE chile.linkedin_posts ENABLE ROW LEVEL SECURITY;

GRANT USAGE, CREATE ON SCHEMA chile TO intranet_chile;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA chile TO intranet_chile;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA chile TO intranet_chile;
GRANT EXECUTE ON FUNCTION chile.marcar_recuperacion_pass(text, text) TO intranet_chile;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    GRANT USAGE ON SCHEMA chile TO service_role;
    GRANT ALL ON ALL TABLES IN SCHEMA chile TO service_role;
    GRANT ALL ON ALL SEQUENCES IN SCHEMA chile TO service_role;
    GRANT EXECUTE ON FUNCTION chile.marcar_recuperacion_pass(text, text) TO service_role;
  END IF;
END$$;

DO $$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT c.relname
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'chile' AND c.relkind = 'r'
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS dashboard_all ON chile.%I', r.relname);
    EXECUTE format(
      'CREATE POLICY dashboard_all ON chile.%I FOR ALL TO postgres USING (true) WITH CHECK (true)',
      r.relname
    );
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon')
       AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
      EXECUTE format('DROP POLICY IF EXISTS deny_postgrest ON chile.%I', r.relname);
      EXECUTE format(
        'CREATE POLICY deny_postgrest ON chile.%I FOR ALL TO anon, authenticated USING (false) WITH CHECK (false)',
        r.relname
      );
    END IF;
  END LOOP;
END$$;

-- IDs: 6 dígitos aleatorios (100000-999999) en entidades visibles (users,
-- tickets, noticias, cursos, vacaciones, eventos, apps). IDENTITY secuencial
-- en internas/catálogo (logs, mensajes Claude, respuestas, áreas, feriados).
-- ensure_id_strategy remapea filas y deja trigger o IDENTITY. No llamar en
-- cada arranque de Node: toma ACCESS EXCLUSIVE en todo el schema.

CREATE OR REPLACE FUNCTION chile.next_six_digit_id(p_table text)
RETURNS integer
LANGUAGE plpgsql
AS $fn$
DECLARE
  candidate integer;
  found_id integer;
  i integer;
BEGIN
  IF p_table IS NULL OR p_table !~ '^[a-z0-9_]+$' THEN
    RAISE EXCEPTION 'tabla inválida para ID de 6 dígitos';
  END IF;
  FOR i IN 1..80 LOOP
    candidate := 100000 + floor(random() * 900000)::integer;
    found_id := NULL;
    EXECUTE format('SELECT 1 FROM chile.%I WHERE id = $1', p_table)
      INTO found_id
      USING candidate;
    IF found_id IS NULL THEN
      RETURN candidate;
    END IF;
  END LOOP;
  RAISE EXCEPTION 'No fue posible generar un ID de 6 dígitos para chile.%', p_table;
END;
$fn$;

CREATE OR REPLACE FUNCTION chile.assign_six_digit_id()
RETURNS trigger
LANGUAGE plpgsql
AS $fn$
BEGIN
  IF NEW.id IS NULL OR NEW.id < 100000 THEN
    NEW.id := chile.next_six_digit_id(TG_TABLE_NAME);
  END IF;
  RETURN NEW;
END;
$fn$;

CREATE OR REPLACE FUNCTION chile.ensure_id_strategy()
RETURNS void
LANGUAGE plpgsql
AS $fn$
DECLARE
  p_schema constant text := 'chile';
  p_role constant text := 'intranet_chile';
  six_digit_tables constant text[] := ARRAY[
    'users', 'support_tickets', 'news_articles', 'courses', 'questions',
    'question_options', 'events', 'applications', 'vacation_requests',
    'vacation_periods'
  ];
  identity_tables constant text[] := ARRAY[
    'change_log', 'claude_conversations', 'claude_messages', 'ticket_replies',
    'vacation_balance_adjustments', 'work_areas', 'lunch_menu', 'public_holidays',
    'documents', 'other_documents', 'study_materials', 'event_photos',
    'linkedin_posts', 'user_course_progress'
  ];
  t record;
  r record;
  rec record;
  fk record;
  tname text;
  candidate integer;
  found_id integer;
  i integer;
  seq_name text;
  max_id integer;
  has_created_at boolean;
  table_ok boolean;
  ident text;
  order_sql text;
BEGIN
  FOR t IN
    SELECT c.relname
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = p_schema AND c.relkind = 'r'
  LOOP
    EXECUTE format('LOCK TABLE %I.%I IN ACCESS EXCLUSIVE MODE', p_schema, t.relname);
  END LOOP;

  DROP TABLE IF EXISTS _id_map;
  DROP TABLE IF EXISTS _fk_backup;
  CREATE TEMP TABLE _id_map (
    table_name text NOT NULL,
    old_id integer NOT NULL,
    new_id integer NOT NULL,
    PRIMARY KEY (table_name, old_id),
    UNIQUE (table_name, new_id)
  ) ON COMMIT DROP;
  CREATE TEMP TABLE _fk_backup (
    table_name text NOT NULL,
    conname text NOT NULL,
    def text NOT NULL
  ) ON COMMIT DROP;

  INSERT INTO _fk_backup (table_name, conname, def)
  SELECT c.relname, con.conname, pg_get_constraintdef(con.oid)
  FROM pg_constraint con
  JOIN pg_class c ON c.oid = con.conrelid
  JOIN pg_namespace n ON n.oid = con.connamespace
  WHERE con.contype = 'f' AND n.nspname = p_schema;

  FOR fk IN SELECT * FROM _fk_backup LOOP
    EXECUTE format('ALTER TABLE %I.%I DROP CONSTRAINT %I', p_schema, fk.table_name, fk.conname);
  END LOOP;

  FOREACH tname IN ARRAY six_digit_tables LOOP
    SELECT EXISTS (
      SELECT 1 FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = p_schema AND c.relkind = 'r' AND c.relname = tname
    ) INTO table_ok;
    IF NOT table_ok THEN
      CONTINUE;
    END IF;

    FOR rec IN EXECUTE format(
      'SELECT id FROM %I.%I WHERE id < 100000 ORDER BY id',
      p_schema, tname
    ) LOOP
      FOR i IN 1..80 LOOP
        candidate := 100000 + floor(random() * 900000)::integer;
        found_id := NULL;
        EXECUTE format('SELECT 1 FROM %I.%I WHERE id = $1', p_schema, tname)
          INTO found_id
          USING candidate;
        EXIT WHEN found_id IS NULL
          AND NOT EXISTS (
            SELECT 1 FROM _id_map m
            WHERE m.table_name = tname AND m.new_id = candidate
          );
        IF i = 80 THEN
          RAISE EXCEPTION 'No fue posible generar un ID de 6 dígitos para %.%', p_schema, tname;
        END IF;
      END LOOP;
      INSERT INTO _id_map (table_name, old_id, new_id)
      VALUES (tname, rec.id, candidate);
    END LOOP;
  END LOOP;

  FOREACH tname IN ARRAY identity_tables LOOP
    SELECT EXISTS (
      SELECT 1 FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = p_schema AND c.relkind = 'r' AND c.relname = tname
    ) INTO table_ok;
    IF NOT table_ok THEN
      CONTINUE;
    END IF;

    EXECUTE format('SELECT COALESCE(MAX(id), 0) FROM %I.%I', p_schema, tname) INTO max_id;
    IF max_id < 100000 THEN
      CONTINUE;
    END IF;

    SELECT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = p_schema AND table_name = tname AND column_name = 'created_at'
    ) INTO has_created_at;
    order_sql := CASE WHEN has_created_at THEN 'created_at, id' ELSE 'id' END;

    EXECUTE
      'INSERT INTO _id_map (table_name, old_id, new_id)
       SELECT $1, s.id, s.rn
       FROM (
         SELECT id, row_number() OVER (ORDER BY ' || order_sql || ')::integer AS rn
         FROM ' || quote_ident(p_schema) || '.' || quote_ident(tname) || '
       ) s
       WHERE s.id IS DISTINCT FROM s.rn'
      USING tname;
  END LOOP;

  FOR r IN
    SELECT
      b.table_name AS child_table,
      (regexp_match(b.def, 'FOREIGN KEY \(([a-z0-9_]+)\)'))[1] AS fk_col,
      (regexp_match(b.def, 'REFERENCES (?:[a-z_]+\.)?([a-z0-9_]+)\(id\)'))[1] AS parent_table
    FROM _fk_backup b
  LOOP
    IF r.fk_col IS NULL OR r.parent_table IS NULL THEN
      CONTINUE;
    END IF;
    IF NOT EXISTS (
      SELECT 1 FROM _id_map m WHERE m.table_name = r.parent_table
    ) THEN
      CONTINUE;
    END IF;
    EXECUTE format(
      'UPDATE %I.%I t SET %I = m.new_id FROM _id_map m WHERE m.table_name = %L AND t.%I = m.old_id',
      p_schema, r.child_table, r.fk_col, r.parent_table, r.fk_col
    );
  END LOOP;

  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = p_schema
      AND table_name = 'vacation_requests'
      AND column_name = 'period_allocations'
  ) THEN
    EXECUTE format(
      $q$
      UPDATE %I.vacation_requests vr
      SET period_allocations = sub.new_alloc
      FROM (
        SELECT vr2.id,
          jsonb_agg(
            CASE
              WHEN m.new_id IS NULL THEN elem
              ELSE jsonb_set(elem, '{periodId}', to_jsonb(m.new_id))
            END
            ORDER BY ordinality
          ) AS new_alloc
        FROM %I.vacation_requests vr2
        CROSS JOIN LATERAL jsonb_array_elements(vr2.period_allocations)
          WITH ORDINALITY AS x(elem, ordinality)
        LEFT JOIN _id_map m
          ON m.table_name = 'vacation_periods'
         AND m.old_id = NULLIF(elem->>'periodId', '')::integer
        WHERE vr2.period_allocations IS NOT NULL
          AND jsonb_typeof(vr2.period_allocations) = 'array'
          AND jsonb_array_length(vr2.period_allocations) > 0
        GROUP BY vr2.id
      ) sub
      WHERE vr.id = sub.id
      $q$,
      p_schema, p_schema
    );
  END IF;

  FOR t IN SELECT DISTINCT table_name FROM _id_map LOOP
    EXECUTE format(
      'UPDATE %I.%I t SET id = m.new_id FROM _id_map m WHERE m.table_name = %L AND t.id = m.old_id',
      p_schema, t.table_name, t.table_name
    );
  END LOOP;

  FOR fk IN SELECT * FROM _fk_backup LOOP
    EXECUTE format(
      'ALTER TABLE %I.%I ADD CONSTRAINT %I %s',
      p_schema, fk.table_name, fk.conname, fk.def
    );
  END LOOP;

  FOR t IN
    SELECT c.relname
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    JOIN pg_index i ON i.indrelid = c.oid AND i.indisprimary
    JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = ANY (i.indkey)
    WHERE n.nspname = p_schema AND c.relkind = 'r'
    GROUP BY c.relname
    HAVING count(*) = 1
       AND min(a.attname) = 'id'
       AND min(a.atttypid) = 'integer'::regtype
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_six_digit_id ON %I.%I', p_schema, t.relname);
  END LOOP;

  FOREACH tname IN ARRAY six_digit_tables LOOP
    SELECT EXISTS (
      SELECT 1 FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = p_schema AND c.relkind = 'r' AND c.relname = tname
    ) INTO table_ok;
    IF NOT table_ok THEN
      CONTINUE;
    END IF;

    seq_name := pg_get_serial_sequence(format('%I.%I', p_schema, tname), 'id');
    EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN id DROP DEFAULT', p_schema, tname);
    BEGIN
      EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN id DROP IDENTITY IF EXISTS', p_schema, tname);
    EXCEPTION
      WHEN undefined_object THEN
        NULL;
    END;
    IF seq_name IS NOT NULL THEN
      EXECUTE format('DROP SEQUENCE IF EXISTS %s', seq_name);
    END IF;

    EXECUTE format(
      'CREATE TRIGGER trg_six_digit_id BEFORE INSERT ON %I.%I FOR EACH ROW EXECUTE FUNCTION chile.assign_six_digit_id()',
      p_schema, tname
    );
  END LOOP;

  FOREACH tname IN ARRAY identity_tables LOOP
    SELECT EXISTS (
      SELECT 1 FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = p_schema AND c.relkind = 'r' AND c.relname = tname
    ) INTO table_ok;
    IF NOT table_ok THEN
      CONTINUE;
    END IF;

    SELECT a.attidentity INTO ident
    FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = p_schema
      AND c.relname = tname
      AND a.attname = 'id'
      AND NOT a.attisdropped;

    IF ident IS NULL OR ident = '' THEN
      EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN id DROP DEFAULT', p_schema, tname);
      EXECUTE format(
        'ALTER TABLE %I.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY',
        p_schema, tname
      );
    END IF;

    seq_name := pg_get_serial_sequence(format('%I.%I', p_schema, tname), 'id');
    EXECUTE format('SELECT COALESCE(MAX(id), 0) FROM %I.%I', p_schema, tname) INTO max_id;
    IF seq_name IS NOT NULL THEN
      IF max_id < 1 THEN
        EXECUTE format('SELECT setval(%L::regclass, 1, false)', seq_name);
      ELSE
        EXECUTE format('SELECT setval(%L::regclass, %s, true)', seq_name, max_id);
      END IF;
    END IF;
  END LOOP;

  EXECUTE format(
    'GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA %I TO %I',
    p_schema, p_role
  );
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    EXECUTE format('GRANT ALL ON ALL SEQUENCES IN SCHEMA %I TO service_role', p_schema);
  END IF;
END;
$fn$;

CREATE OR REPLACE FUNCTION chile.ensure_six_digit_ids()
RETURNS void
LANGUAGE plpgsql
AS $fn$
BEGIN
  PERFORM chile.ensure_id_strategy();
END;
$fn$;

ALTER FUNCTION chile.next_six_digit_id(text) SET search_path = chile, pg_temp;
ALTER FUNCTION chile.assign_six_digit_id() SET search_path = chile, pg_temp;
ALTER FUNCTION chile.ensure_id_strategy() SET search_path = chile, pg_temp;
ALTER FUNCTION chile.ensure_six_digit_ids() SET search_path = chile, pg_temp;

REVOKE ALL ON FUNCTION chile.next_six_digit_id(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION chile.assign_six_digit_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION chile.ensure_id_strategy() FROM PUBLIC;
REVOKE ALL ON FUNCTION chile.ensure_six_digit_ids() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION chile.next_six_digit_id(text) TO intranet_chile;
GRANT EXECUTE ON FUNCTION chile.assign_six_digit_id() TO intranet_chile;
GRANT EXECUTE ON FUNCTION chile.ensure_id_strategy() TO intranet_chile;
GRANT EXECUTE ON FUNCTION chile.ensure_six_digit_ids() TO intranet_chile;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
    GRANT EXECUTE ON FUNCTION chile.next_six_digit_id(text) TO service_role;
    GRANT EXECUTE ON FUNCTION chile.assign_six_digit_id() TO service_role;
    GRANT EXECUTE ON FUNCTION chile.ensure_id_strategy() TO service_role;
    GRANT EXECUTE ON FUNCTION chile.ensure_six_digit_ids() TO service_role;
  END IF;
END$$;

SELECT chile.ensure_id_strategy();
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA chile TO intranet_chile;
